//! Shared harness for the integration tests.
//!
//! Runs a real `App` with real asset loading, headless: no window, no GPU. The
//! fixtures in `assets/levels/` are plain-text glTF generated by
//! `tools/gen_test_levels.py`.

#![allow(dead_code)]

use bevy::asset::{AssetPlugin, LoadState};
use bevy::gltf::{Gltf, GltfPlugin};
use bevy::prelude::*;
use bevy::world_serialization::{WorldAssetRoot, WorldSerializationPlugin};

use bevy_stage::prelude::*;

/// A headless app with everything a glTF level needs and nothing else.
pub fn test_app() -> App {
    let mut app = App::new();
    app.add_plugins((
        MinimalPlugins,
        TransformPlugin,
        AssetPlugin::default(),
        ImagePlugin::default(),
        bevy::mesh::MeshPlugin,
        bevy::camera::CameraPlugin,
        bevy::light::LightPlugin,
        WorldSerializationPlugin,
        GltfPlugin::default(),
        StagePlugin::default(),
    ));

    // `LightPlugin` brings gizmo systems with it when Bevy's gizmo feature is
    // enabled, which it is because the examples need Bevy's default features.
    // Those systems want this asset and `GizmoPlugin` needs a renderer, so
    // register the asset directly rather than drag a GPU into a headless test.
    app.init_asset::<bevy::gizmos::GizmoAsset>();
    app
}

/// Finish plugin setup. Driving an `App` by hand never calls these, and
/// `GltfPlugin` registers its asset loader in `finish`, so without them
/// nothing ever loads.
pub fn start(app: &mut App) {
    app.finish();
    app.cleanup();
}

/// Run until `done`, failing with a clear message rather than hanging.
pub fn run_until(app: &mut App, label: &str, mut done: impl FnMut(&mut App) -> bool) {
    for _ in 0..600 {
        app.update();
        if done(app) {
            return;
        }
        std::thread::sleep(std::time::Duration::from_millis(2));
    }
    panic!("timed out waiting for {label}");
}

/// Load a glTF and wait for it, returning the handle.
pub fn load_gltf(app: &mut App, path: &str) -> Handle<Gltf> {
    let handle: Handle<Gltf> = app.world().resource::<AssetServer>().load(path.to_string());
    let owned = path.to_string();
    run_until(app, &format!("`{owned}` to load"), |app| {
        match app.world().resource::<AssetServer>().load_state(&handle) {
            LoadState::Loaded => true,
            LoadState::Failed(error) => panic!("failed to load {owned}: {error}"),
            _ => false,
        }
    });
    handle
}

/// Load a level, spawn its default scene, and wait for tags to resolve.
pub fn spawn_level(app: &mut App, path: &str) -> Entity {
    let handle = load_gltf(app, path);
    let scene = app
        .world()
        .resource::<Assets<Gltf>>()
        .get(&handle)
        .expect("asset present once loaded")
        .default_scene
        .clone()
        .expect("fixture declares a default scene");

    let root = app.world_mut().spawn(WorldAssetRoot(scene)).id();

    run_until(app, "the scene to spawn and resolve", |app| {
        let spawned = app.world_mut().query::<&StageTags>().iter(app.world()).count() > 0;
        spawned
            && app
                .world()
                .resource::<bevy_stage::tag::StageTagQueue>()
                .is_empty()
    });
    app.update();
    root
}

/// Run until a stage reaches [`StageStatus::Ready`], failing loudly if the
/// load failed rather than silently timing out.
pub fn wait_for_stage(app: &mut App, id: bevy_stage::stage::StageId) {
    use bevy_stage::stage::{StageRoot, StageStatus};

    run_until(app, &format!("stage {id:?} to become ready"), |app| {
        let mut query = app.world_mut().query::<&StageRoot>();
        let status = query
            .iter(app.world())
            .find(|root| root.id == id)
            .map(|root| root.status.clone());
        match status {
            Some(StageStatus::Failed(error)) => panic!("stage {id:?} failed to load: {error}"),
            Some(StageStatus::Ready) => true,
            _ => false,
        }
    });
}

/// The world transform of a named anchor belonging to a given stage.
pub fn anchor_in_world(
    app: &mut App,
    stage: bevy_stage::stage::StageId,
    anchor_id: &str,
) -> GlobalTransform {
    use bevy_stage::stage::{StageAnchor, StageManager, StageRoot};

    let root_entity = app
        .world()
        .resource::<StageManager>()
        .entity(stage)
        .expect("stage is resident");

    let mut query = app
        .world_mut()
        .query::<(Entity, &StageAnchor, &GlobalTransform)>();
    let candidates: Vec<(Entity, GlobalTransform)> = query
        .iter(app.world())
        .filter(|(_, anchor, _)| anchor.id == anchor_id)
        .map(|(entity, _, transform)| (entity, *transform))
        .collect();

    // A level can be resident twice, so pick the anchor under the right root.
    for (entity, transform) in candidates {
        if is_descendant_of(app, entity, root_entity) {
            return transform;
        }
    }
    let _ = app.world_mut().query::<&StageRoot>();
    panic!("no anchor `{anchor_id}` found under stage {stage:?}");
}

fn is_descendant_of(app: &mut App, mut entity: Entity, ancestor: Entity) -> bool {
    loop {
        if entity == ancestor {
            return true;
        }
        match app.world().get::<ChildOf>(entity) {
            Some(parent) => entity = parent.parent(),
            None => return false,
        }
    }
}
